env:
  browser: false
  es6: true
  jest: true
extends:
  - airbnb-base
  - prettier
  - plugin:jsdoc/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - jest
  - prettier
<<<<<<< HEAD
  - prefer-arrow
  - jsdoc
rules:
  {
    prettier/prettier: ['error'],
    prefer-arrow/prefer-arrow-functions:
      [
        'error',
        { 'disallowPrototype': true, 'singleReturnOnly': false, 'classPropertiesAllowed': false },
      ],
  }
=======
rules: { prettier/prettier: ['error'] }
>>>>>>> feat(prettier): adding increased support for prettier
