env:
  browser: false
  es6: true
  jest: true
extends:
  - airbnb-base
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - jest
  - prettier
rules: {
    prettier/prettier: ["error"]
  }
